# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

site_name: Factory Orchestrator
site_author: themar-msft;hajya
repo_url: https://github.com/microsoft/FactoryOrchestrator
site_description: "Factory Orchestrator Documentation"
site_url: 'https://microsoft.github.io/FactoryOrchestrator/'
plugins:
    - search

theme: 
  name: material
  logo: 'images/fo-logo.png'
  favicon: 'images/fo-logo.png'
  palette:
    primary: 'blue grey' 
    accent: 'amber'

nav: 
  - Overview: 'index.md' 
  - Get Started: 'get-started-with-factory-orchestrator.md'
  - Tasks & TaskLists : 'tasks-and-tasklists.md'
  - Service configuration : 'service-configuration.md'
  - Using the application: 'use-the-factory-orchestrator-app.md'
  - Writing PowerShell or C# code:
      - Factory Orchestrator API overview: 'use-the-factory-orchestrator-api.md'
      - PowerShell and C# code samples: 'factory-orchestrator-client-usage-samples.md'
      - Client Library Class Reference: 'ClientLibrary\Microsoft_FactoryOrchestrator_Client.md'
      - Core Library Class Reference: 'CoreLibrary\Microsoft_FactoryOrchestrator_Core.md'
  - Find Factory Orchestrator devices: 'find-factory-orchestrator-devices.md'
  - Uninstall Factory Orchestrator: 'uninstall-factory-orchestrator.md'
  
